name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build project with debug flags
      run: |
        echo $PWD
        cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles"
        echo $PWD
        cmake --target CppGitHubCICDByExample
