name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build project with debug flags
      run: |
        mkdir cmake-build-debug
        cmake -DCMAKE_BUILD_TYPE=Debug
        cmake --build cmake-build-debug --target CppGitHubCICDByExample -- -j$(nproc)
