name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        buildtype: [Debug, Release, MinSizeRel]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake -p cmake-build-debug -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} -G "CodeBlocks - Unix Makefiles" $PWD
    - name: build
      run: cmake --build . --target CppGitHubCICDByExample
    - name: run
      run: ./CppGitHubCICDByExample
